### ISSUE TITLE
Need Description on implementation

### ISSUE THREAD

**Issue by joelvzach** [biswaz/ktu-alert#53]
Hey Biswaz! Your idea to optimize and retrieve data from KTU website is good. It would be useful to the public if there was a short description on how to implement the script to make use of. My apologies in case the request sounds unnecessary and is expected to be used only by those who know. Look forward to a response. I am willing to contribute in case you require help in the future. Thank You

**Comment by biswaz** [comment]
Hi Joel.
I've updated the README. You can ask your doubts here, if it is not sufficient.
Ideas for improvement are always welcome.
